config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'
  devise_for :users

  resources :portfolios do 
    resources :stocks 
  end
  
  resources :portfolios do
    resources :orders 
  end

  resources :stocks
  resources :orders

  put '/complete', to: 'stocks#complete', as: 'complete'
  get '/managers/:id/filter', to: 'stocks#filter', as: 'managers_filter'
  get '/portfolios/:portfolio_id/industry/:slug', to: 'stocks#industry', as: 'portfolio_industry'
  get '/portfolios/:id/industries', to: 'stocks#industries', as: 'industries'
  get '/search/:symbol', to: 'stocks#search', as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :orders
    belongs_to :user

#     attr_accessor :manager_id

#     def self.set_manager_id
#         User.all.where(manager: true).sample.id
#     end

    def get_current_prices
        # grabs the users held stocks and makes api requests for to get current prices for each one
        self.orders.map do |o|
            response = Stock.find_from_api(o.symbol)
            o.share_price = response["price"]
            o.balance = response["price"].to_f * o.number_of_shares.to_f
            o.save
        end
        self.save
    end

    def return_percentage
        # return total portfolio return percentage
        if self.current_balance == self.balance 
            "Invest today!"
        elsif self.holdings.to_f + self.current_balance.to_f < self.balance 
             (1.00 - (self.current_balance.to_f + self.holdings.to_f) / self.balance.to_f) * 100
        else
            (self.current_balance.to_f + self.holdings.to_f) / self.balance.to_f
        end
    end

    def direction
        # returns up or down to signal which way the portfolio is going
        self.current_balance + self.holdings > self.balance ? "Up" : "Down"
    end

    def holdings 
        # return total holdings for each stock combined
        # .inspect was returning nil?
        sum = 0
        self.orders.each do |o|
            if o.status == "success" || o.status == "pending sale"
                sum += o.balance.to_f
            end
        end
        sum 
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

    def index
        if current_user.portfolios.empty? && !current_user.manager_role
            redirect_to new_portfolio_path
        else
           @portfolios = current_user.portfolios
        end
    end

    def new
        @portfolio = Portfolio.new
    end

    def create
        @portfolio = Portfolio.new(portfolio_params)
        @portfolio.current_balance = @portfolio.balance
        @portfolio.user_id = current_user.id 
        @portfolio.save
        redirect_to portfolio_path(@portfolio)
    end

    def show
        @portfolio = Portfolio.find(params[:id])
        @portfolio.get_current_prices
    end

    private 

    def portfolio_params
        params.require(:portfolio).permit(:name, :balance, :current_balance)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/index.html.erb
<div id="portfolio-index-container" class="portfolio-container">
    <header>
        <% if current_user.manager_role %>
            <h1>Customer Portfolios</h1>
        <% else %>
            <h1>Portfolios</h1>
        <% end %>
        <div class="sign-links">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav" %>
            <% if can? :filter, Stock %>
                <%=  link_to 'Filter Stocks', managers_filter_path(current_user), class: "nav" %>
            <% end %>
        </div>
    </header>

    <div class="portfolios-container">
        <% if can? :crud, User %>
            <% Portfolio.all.each do |p| %>
                <% if p.manager_id == current_user.id %>
                        <div class="customer-portfolio-container">
                            <div class="customer-portfolios-list">
                                <h1><a href="/portfolios/<%=p.id%>"><%= p.user.username %></a></h1>
                                <% p.orders.each do |o| %>
                                    <% if o.status == "pending" %>
                                        <p>Purchase Order: <%= link_to(o.symbol, edit_portfolio_order_path(portfolio_id: o.portfolio.id, id: o.id)) %></p>
                                    <% elsif o.status == "pending sale" %>
                                        <p>Pending Sale: <%= link_to(o.symbol, edit_portfolio_order_path(portfolio_id: o.portfolio.id, id: o.id)) %></p>
                                    <% end %>
                                <% end %>
                                <div class="portfolio-info">
                                    <% if p.direction == "Down" %> 
                                        <p class="down"><%= p.direction %></p>
                                    <% else %>
                                        <p class="up"><%= p.direction %></p>
                                    <% end %>
                                    <p> <%= number_with_precision(p.return_percentage, precision: 2) %></p>
                                </div>
                            </div>
                        </div>
                <% end %>
            <% end %>
        <% else %>
            <% @portfolios.each do |p| %>
                <a href="/portfolios/<%= p.id %>">
                    <div class="portfolios-list">
                        <h1><%= p.name.capitalize %></h1>
                        <div class="portfolio-info">
                           <% if p.direction == "Down" %> 
                                <p class="down"> <%= p.direction %></p>
                            <% else %>
                                <p class="up"><%= p.direction %></p>
                            <% end %>
                            <p> <%= number_with_precision(p.return_percentage, precision: 2) %>%</p>
                        </div>
                    </div>
                </a>
            <% end %>
        <% end %>
    </div>

</div>

app/views/portfolios/new.html.erb
<%= link_to 'My Portfolios', portfolios_path %>|<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

<%= form_for @portfolio do |f| %>
    Portolio Name:<%= f.text_field :name %>
    Account Balance: <%= f.text_field :balance %>
    <%= f.submit %>
<% end %>

app/views/portfolios/show.html.erb
<div id="portfolio-show-container" class="portfolio-container">
    <header>
        <div class="user">
            <h1>Hi, <%= current_user.username %>.<h1>
            <h3><%= @portfolio.name.capitalize %> Account / </h3>    
            <% if @portfolio.direction == "Down" %>
                <h3 class="down"> <%= @portfolio.direction %></h3>
            <% else %>
                <h3 class="up"> <%= @portfolio.direction %></h3>
            <% end %> 
            <h3> <%= number_with_precision(@portfolio.return_percentage, precision: 2) %>%</h3>
        </div>
        <div class="sign-links show">
            <%= link_to 'My portfolios', portfolios_path, class: "nav" %> 
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav" %> 
            <% if can? :crud, User %> 
                <%= link_to 'Delete Portfolio', @portfolio, method: "delete", data: { confirm: "Are you sure?" }, class: "nav" %>
            <% end %>
        </div>
    </header> 

    <div>
        <div id="balance-info">
            <% if current_user.manager_role == true  %>
                <span>Manager Permissions</span>
            <% end %>
            <span>Trading Balance: $<%= number_with_precision(@portfolio.current_balance, precision: 2) %></span> 
            <span>Holdings: $<%= number_with_precision(@portfolio.holdings, precision: 2) %></span>
            <span><%= link_to 'Research Stocks', industries_path(@portfolio) %></span>
        </div>

        <div class="stocks-container">
            <% if @portfolio.orders.empty? %>
                Your portfolio is empty.
            <% else %>
                <div class="orders-container">
                    <% @portfolio.orders.each do |order| %>
                        <div class="order-stock">
                            <h3><%= link_to "#{order.symbol} - #{order.name}", stocks_path(portfolio_id: @portfolio.id, slug: order.symbol) %></h3>

                            <div class="order-info">
                                <p>Total: <strong>$<%= number_with_precision((order.share_value), precision: 2) %></strong></p>
                                <p>Shares: <strong><%= order.number_of_shares %></strong></p>
                                <p>
                                    <% if order.status == "success" %>
                                        <%= link_to 'Request Sale', edit_portfolio_order_path(portfolio_id: @portfolio.id, id: order.id) %>
                                    <% elsif order.status == "pending" %>
                                        Status: Pending <%= link_to 'Cancel Trade', portfolio_order_path(portfolio_id: @portfolio.id, id: order.id), :method => :delete %>
                                    <% elsif order.status == "rejected" %>
                                        Status: Rejected <%= link_to 'Delete', portfolio_order_path(portfolio_id: @portfolio.id, id: order.id), :method => :delete %>
                                    <% elsif order.status == "pending sale" %>
                                        Status: Pending Sale
                                    <% else %>
                                        Status: Sold <%= link_to 'Delete', portfolio_order_path(portfolio_id: @portfolio.id, id: order.id), :method => :delete %>
                                    <% end %>
                                </p>
                                <% if order.status == "pending" %>
                                    <p>Held at: $<%= number_with_precision(order.purchase_price, precision: 2) %></p>
                                <% else %>
                                    <p>Bought at: $<%= number_with_precision(order.purchase_price, precision: 2) %></p>
                                <% end %>

                                <p>Current Price: <strong>$<%= number_with_precision(order.share_price, precision: 2) %></strong></p> 

                                <p><%= order.order_return_percentage %></p>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>

</div>