config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'
  devise_for :users

  resources :portfolios do 
    resources :stocks 
  end
  
  resources :portfolios do
    resources :orders 
  end

  resources :stocks
  resources :orders

  put '/complete', to: 'stocks#complete', as: 'complete'
  get '/managers/:id/filter', to: 'stocks#filter', as: 'managers_filter'
  get '/portfolios/:portfolio_id/industry/:slug', to: 'stocks#industry', as: 'portfolio_industry'
  get '/portfolios/:id/industries', to: 'stocks#industries', as: 'industries'
  get '/search/:symbol', to: 'stocks#search', as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord

    @endpoint = ENV['av_api_key']

    #rembmer to remove stocks w/ weird characters in their symbols

    def self.alter_api_keys(response)
        stock = {}
        response.each do |k, v|
            stock[k.sub(/\d.. /, '')] = v
        end
        stock
    end

    def self.group_by_industry 
        industries = {}
        #groups all stocks by industries to be displayed
        Stock.all.each do |stock|
            if !industries[stock[:industry]]
                industries[stock[:industry]] = []
            else 
                industries[stock[:industry]] << stock unless industries[stock[:industry]].include?(stock)
            end
        end
        industries
    end

    def self.find_from_api(symbol) 
        #uses symbol to return stock data from api
        response = Request.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{symbol}&apikey=#{@endpoint}")
        if response["Note"]
            "API LIMIT REACHED"
        else
            #alters api keys so they can be parsed
            alter_api_keys(response["Global Quote"])
        end
    end

    def self.search(symbol)
        # response = Request.get("?function=SYMBOL_SEARCH&keywords=#{symbol}&apikey=#{@endpoint}")
        # @stock = Stock.new(stock_hash)
        # @stock.save
        # @stock
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    load_and_authorize_resource :except => [:index]

    rescue_from CanCan::AccessDenied do |exception|
        flash[:error] = "Access denied."
        redirect_to portfolio_path(params[:portfolio_id])
    end

    def index 
        if current_user
            stock = Stock.find_by(symbol: params[:slug])
            portfolio = Portfolio.find(params[:portfolio_id])
            redirect_to portfolio_stock_path(portfolio_id: portfolio.id, id: stock.id)
        else
            @stocks = Stock.all 
        end
    end

    def filter
        @stocks = Stock.all
    end

    def show
        @portfolio = Portfolio.find(params[:portfolio_id])
        @stock = Stock.find(params[:id])
        @prices = Stock.find_from_api(@stock.symbol)
    end

    def industries 
        @portfolio = Portfolio.find(params[:id])
        @industries = Stock.group_by_industry
    end

    def industry
        @portfolio = Portfolio.find(params[:portfolio_id])
        @industry_name = params[:slug]
        @industry = Stock.all.where(industry: params[:slug])
    end

    def complete
        # filter stocks by ids
        stock_ids = params[:stock][:id]
        Stock.all.each do |stock|
            if stock_ids.include?(stock.id.to_s)
                stock.available = false
                stock.save
            end
        end
        redirect_to portfolios_path
    end
    
    def search 
        @stock = Stock.search(params[:symbol])
    end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/filter.html.erb
<div id="filter-div">
    <h3><%= link_to 'Home', portfolios_path %></h3>
    <u><h1>Check boxes to make stocks unavailable<h1></u>
    <%= form_for :stock, url: complete_path, method: :put, :html => { :class => "filter-form"} do |f| %>
        <%= f.collection_check_boxes(:id, Stock.all, :id, :name) do |s| %>
            <%= s.label class:"label-checkbox grid-item" do %>
                <%= s.check_box + s.text %>
            <% end %>
        <% end  %>
        <%= f.submit "FILTER STOCKS" %>
    <% end %>
</div>

app/views/stocks/index.html.erb
<div class="index-container">
    <navbar class="nav grid-container">
        <div class="sign-links">
            <% if current_user %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav" %>
            <% else %>
                <%= link_to 'Sign up', new_user_registration_path, class: "nav" %>
                <%= link_to 'Sign in', new_user_session_path, class: "nav" %>
            <% end %>
        </div>
        <h1>cstocks</h1>
    </navbar>

    <%= content_tag :div, class: "stock-list-container grid-container" do %>
        <% @stocks.sort_by do |stock| %>
            <a href="/stocks/<%= stock.id %>" >
                <div class="stock grid-item" >
                    <p class="stock-symbol"><%= stock.symbol %></p>
                    <p class="stock-name"><%= stock.name.gsub('&#39;', '\'') %></p>
                </div>
            </a>
        <% end %>
    <% end %>
</div>

app/views/stocks/industries.html.erb
<div id="industries-container">
    <h1>Industries</h1>
    <%= content_tag :ul, class: "industries-list" do %>
        <% @industries.each do |ind, stocks| %>
            <% if ind == 'n/a' %>
            <%= link_to(content_tag(:li, 'Other'), portfolio_industry_path(portfolio_id: @portfolio.id, slug: ind), class: "grid-item") %>
            <% else %>
            <%= link_to(content_tag(:li, ind), portfolio_industry_path(portfolio_id: @portfolio.id, slug: ind), class: "grid-item") %>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/stocks/industry.html.erb
<div id="industries-container">
    <h1><%= @industry_name %></h1>
    <%= content_tag :ul, class: "industry-stock-list" do %>
        <% @industry.each do |stock| %>
            <%= link_to(content_tag(:li, stock.symbol), portfolio_stock_path(portfolio_id: @portfolio.id, id: stock.id), class: "grid-item") %> <%= stock.name %>
        <% end %>
    <% end %>
</div>

app/views/stocks/search.html.erb
<%= @stock.name %>

app/views/stocks/show.html.erb
<div class="sign-links">
    <%= link_to 'Back to Portfolio', portfolio_path(@portfolio), class: "nav" %> 
</div>

<div class="form-container">
    <div class="stock-info">
        <h1><%= @stock.symbol %></h1>
        <h2><%= @stock.name %></h2>
        <h3>Current Price: $<span class="price"><%= @prices["price"] %></span></h3>
        <%= link_to 'Read More', @stock.summary_quote, target: :_blank %>
    </div>

    <% if @stock.available %>
        <h3>Request Trade:<h3>
        <%= form_for @portfolio.orders.build, :html => { :class => "edit-form" } do |o| %>
            <%= o.label :number_of_shares %>
            <%= o.number_field :number_of_shares %>
            <%= o.hidden_field :symbol, :value => @stock.symbol %>
            <%= o.hidden_field :portfolio_id, :value => @portfolio.id %>
            <%= o.hidden_field :share_price, :value => @prices["price"]%>
            <%= o.hidden_field :purchase_price, :value => @prices["price"] %>
            <%= o.hidden_field :name, :value => @stock.name %>
            <%= o.submit 'Request Trade' %>
        <% end %>
    <% else %>
        <h3>Stock Unavailable</h3>
    <% end %>
<div>